// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.9
// source: db.proto

package svc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DbRepoSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SyncData *RepoSync `protobuf:"bytes,1,opt,name=sync_data,json=syncData,proto3" json:"sync_data,omitempty"`
	Stat     *SyncStat `protobuf:"bytes,2,opt,name=stat,proto3" json:"stat,omitempty"`
}

func (x *DbRepoSync) Reset() {
	*x = DbRepoSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DbRepoSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbRepoSync) ProtoMessage() {}

func (x *DbRepoSync) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbRepoSync.ProtoReflect.Descriptor instead.
func (*DbRepoSync) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{0}
}

func (x *DbRepoSync) GetSyncData() *RepoSync {
	if x != nil {
		return x.SyncData
	}
	return nil
}

func (x *DbRepoSync) GetStat() *SyncStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

var File_db_proto protoreflect.FileDescriptor

var file_db_proto_rawDesc = []byte{
	0x0a, 0x08, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x69, 0x74, 0x72,
	0x69, 0x6d, 0x2e, 0x73, 0x76, 0x63, 0x1a, 0x09, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x69, 0x0a, 0x0a, 0x44, 0x62, 0x52, 0x65, 0x70, 0x6f, 0x53, 0x79, 0x6e, 0x63, 0x12,
	0x31, 0x0a, 0x09, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x69, 0x74, 0x72, 0x69, 0x6d, 0x2e, 0x73, 0x76, 0x63, 0x2e,
	0x52, 0x65, 0x70, 0x6f, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x08, 0x73, 0x79, 0x6e, 0x63, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x28, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x69, 0x74, 0x72, 0x69, 0x6d, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x53, 0x79,
	0x6e, 0x63, 0x53, 0x74, 0x61, 0x74, 0x52, 0x04, 0x73, 0x74, 0x61, 0x74, 0x42, 0x20, 0x5a, 0x1e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x61, 0x72, 0x64, 0x72,
	0x65, 0x61, 0x6d, 0x2f, 0x67, 0x69, 0x74, 0x72, 0x69, 0x6d, 0x2f, 0x73, 0x76, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_db_proto_rawDescOnce sync.Once
	file_db_proto_rawDescData = file_db_proto_rawDesc
)

func file_db_proto_rawDescGZIP() []byte {
	file_db_proto_rawDescOnce.Do(func() {
		file_db_proto_rawDescData = protoimpl.X.CompressGZIP(file_db_proto_rawDescData)
	})
	return file_db_proto_rawDescData
}

var file_db_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_db_proto_goTypes = []interface{}{
	(*DbRepoSync)(nil), // 0: gitrim.svc.DbRepoSync
	(*RepoSync)(nil),   // 1: gitrim.svc.RepoSync
	(*SyncStat)(nil),   // 2: gitrim.svc.SyncStat
}
var file_db_proto_depIdxs = []int32{
	1, // 0: gitrim.svc.DbRepoSync.sync_data:type_name -> gitrim.svc.RepoSync
	2, // 1: gitrim.svc.DbRepoSync.stat:type_name -> gitrim.svc.SyncStat
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_db_proto_init() }
func file_db_proto_init() {
	if File_db_proto != nil {
		return
	}
	file_svc_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_db_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DbRepoSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_db_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_db_proto_goTypes,
		DependencyIndexes: file_db_proto_depIdxs,
		MessageInfos:      file_db_proto_msgTypes,
	}.Build()
	File_db_proto = out.File
	file_db_proto_rawDesc = nil
	file_db_proto_goTypes = nil
	file_db_proto_depIdxs = nil
}
